name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Nodejs ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        env:
          CI: true
        run: npm install
      - name: Build
        run: npm run build
